### PR TITLE
Enable code to run in both google colab and in local system

### LINKED ISSUE #371: [Bug]: Enable code to run outside Google colab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I ran the code on my local system it raised an error of importing google colab. I wanted it to run outside google colab as well so I modified the code for that. Please assign it to me
Screenshot 2024-10-02 230521

### Add ScreenShots

Screenshot 2024-10-02 230742

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by shristirwt**
Enable the JobSatisfaction code run both on google colab as well as local system
I found that the code was not running in my local system so I changed it a little bit so that it works both on google colab as well as local environment
Fixes #371

### CODE REVIEW

**Comment by sanjay-kv** [comment]
were is the respective issue for this PR @shristirwt

**Comment by shristirwt** [comment]
@sanjay-kv I have updated the PR

**Review by sanjay-kv — APPROVED** [review]

**Comment by shristirwt** [comment]
Dear @sanjay-kv ,
I had made this pull request but you did not put any labels at the time of merging which lead to the fact that this pull request did not get counted on my GSSoC 2024 Extd leaderboard. I request you to do so if it can be done now. Thank you for your support.

Screenshot 2024-10-06 075324

**Comment by sanjay-kv** [comment]
@shristirwt sorry, i missed it , thanks for highlighting . I fixed it

**Pull request merged**
