### PR TITLE
Added charts to OpenSourceAnalysis 

### PR DESCRIPTION
**Pull request by SimranShaikh20**
Issue no - #406 

@sanjay-kv  i have added eda to open source analysis .
is there any conflits .

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
we dont want new folder structure, i was thinking you would be adding this to existing website as an enhancment

**Comment by SimranShaikh20** [comment]
@sanjay-kv so i have make changes in app. py file right? 
To eda in to that file!

**Comment by SimranShaikh20** [comment]
@sanjay-kv can you please give me clarity where I have to add eda of open source either on note book file or in app. py file?

**Comment by SimranShaikh20** [comment]
@sanjay-kv  pls let me know where I have to make changes

**Comment by sanjay-kv** [comment]
everything should go to app.py

**Comment by SimranShaikh20** [comment]
@sanjay-kv 
So where I have to add images of charts either  I have to create new folder for that Or to add in existing folder only?

**Comment by SimranShaikh20** [comment]
@sanjay-kv 
So only code I have to add ? 
And whether I have to add charts?

**Comment by sanjay-kv** [comment]
tbh it should work like enhancement . 
means addition to the website. which includes charts and stuff. raise a another PR with readme change, I will give label for your work and close the PR

**Pull request closed without merging**
