### PR TITLE
Resolved variable, type and declaration errors

### LINKED ISSUE #395: [Bug]: Deprecation Warning: Use of fillna(method='ffill') Deprecated in Pandas
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While executing the code it displayed an error that Series.fillna is deprecated and we need to use obj.ffill or obj.bfill instead

Screenshot 2024-10-14 211743

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### LINKED ISSUE #396: [Bug]: TypeError: Function Parameter Mismatch Due to Conflicting Definitions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There were two functions having the same name but different number of arguments which when called displayed an error of arguments mismatch

Screenshot 2024-10-14 220637

### Add ScreenShots

Screenshot 2024-10-14 221117

Screenshot 2024-10-14 221126

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### LINKED ISSUE #397: [Bug]: Uninitialized Variable Error: Variable Used Before Declaration in Function Call
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a function which has been called before the variables inside the function have been declared.
It is resulting in an error

Screenshot 2024-10-14 223356

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by shristirwt**
Modified code to resolve variable, type and declaration errors  
fixes #395 , fixes #396 , fixes #397

### CODE REVIEW

**Comment by sanjay-kv** [comment]
@shristirwt I would like to invite you as a maintainer for this repo , would you be interested @shristirwt

**Comment by shristirwt** [comment]
@sanjay-kv Thank you for such a great opportunity . I would love to join as a maintainer

**Comment by sanjay-kv** [comment]
could you connect with me on linkedin: https://www.linkedin.com/in/sanjay-k-v/

**Comment by shristirwt** [comment]
Yeah sure

**Pull request merged**
