### PR TITLE
added charts for job satisfaction analysis #390 

### PR DESCRIPTION
**Pull request by SimranShaikh20**
@sanjay-kv 
Issue no  #390
 I have added entire charts for job satisfaction analysist in a folder .

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by SimranShaikh20** [comment]
@sanjay-kv 
Label is not updated!

**Comment by SimranShaikh20** [comment]
@sanjay-kv  my assigned label is not updated

**Comment by sanjay-kv** [comment]
done

**Comment by SimranShaikh20** [comment]
> done

Yes but in my leaderboard it's not uldated

**Comment by MastanSayyad** [comment]
Hi @SimranShaikh20 

These are you PRs count on the leaderboard with score 60

image

I reviewed your profile and I found out that you have created only  5 PRs till now, out of which only 3 has been successfully merged with level 2, level 2 and level 1 = 60 points and other two are closed 

image

Please know that the leaderboard updates twice a day (morning and evening) and as you cam see above @sanjay-kv removed level 1 from you PR and added level 2 so your count is now 75, which will be reflected in the next server update

**Comment by SimranShaikh20** [comment]
@MastanSayyad 
okay got it

**Comment by SimranShaikh20** [comment]
@MastanSayyad 
All issue are solved 👍

**Pull request merged**
